/**
 * gen-fonts.mjs — regenerate src/fonts.ts from assets/fonts/*.ttf
 *
 * The card renderer needs Liberation Sans (a metric-compatible Arial substitute)
 * available with zero filesystem/system-font dependency, so it works identically
 * when installed from npm AND when bundled into a Bun-compiled standalone binary.
 *
 * We gzip + base64 each TTF and inline it as a string constant. At runtime the
 * bytes are gunzipped and handed to opentype.js's in-memory parser — no temp files.
 *
 * Run after changing the fonts:  node scripts/gen-fonts.mjs
 */
import fs from 'node:fs'
import zlib from 'node:zlib'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const fontsDir = resolve(__dirname, '../assets/fonts')
const outFile = resolve(__dirname, '../src/fonts.ts')

function embed(file) {
  return zlib.gzipSync(fs.readFileSync(resolve(fontsDir, file)), { level: 9 }).toString('base64')
}

const REGULAR = embed('LiberationSans-Regular.ttf')
const BOLD = embed('LiberationSans-Bold.ttf')

const banner = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Source: assets/fonts/LiberationSans-{Regular,Bold}.ttf (gzip + base64).
// Liberation Sans is SIL OFL / GPL licensed — see assets/fonts/LICENSE.
/* eslint-disable */
`

fs.writeFileSync(
  outFile,
  `${banner}export const REGULAR_TTF_GZ_B64 = ${JSON.stringify(REGULAR)}\nexport const BOLD_TTF_GZ_B64 = ${JSON.stringify(BOLD)}\n`,
)
console.log(`wrote ${outFile} (regular ${REGULAR.length} b64 chars, bold ${BOLD.length})`)
